### ISSUE TITLE
No nomad job even if deploy is successful

### ISSUE THREAD

**Issue by pdomineaux** [wescale/hashistack#99]
Hello,

Thank you for that work and for the share.
I've successfully deploy the stack on scaleway. All lights are green but I can not find any nomad job.
The count dashboard app is not deployed.
Did I miss something ?

**Comment by Ronan-WeScale** [comment]
Hi !  
Where did you find we deploy count dashboard sample app ? 

Also we work in background (no issue) to add a sample app in the default deployment.

Regards,

Ronan
